"use client";

import React, { useEffect, useState } from "react";
import { BookOpen, Download, User, Loader2 } from "lucide-react";
import { fetchApi } from "../../../lib/api";
import { GlassCard } from "../../components/ui/GlassCard";
import { Button } from "../../components/ui/Button";

export default function PublicationsPage() {
  const [publications, setPublications] = useState([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  useEffect(() => {
    const loadPublications = async () => {
      setLoading(true);
      try {
        const result = await fetchApi(`/v1/publications?page=${page}&limit=6`);
        if (result && result.data) {
          setPublications(result.data);
          setTotalPages(result.meta.totalPages);
        }
      } catch (err) {
        console.error("Failed to load publications", err);
      } finally {
        setLoading(false);
      }
    };
    loadPublications();
  }, [page]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <Loader2 className="w-10 h-10 text-primary animate-spin" />
      </div>
    );
  }

  return (
    <div className="w-full min-h-screen bg-background text-foreground py-24 px-6 lg:px-12">
      <div className="max-w-7xl mx-auto flex flex-col gap-12">
        {/* Header */}
        <div className="flex flex-col gap-4 animate-in fade-in slide-in-from-bottom-4 duration-700">
          <div className="flex items-center gap-3 text-primary mb-2">
            <BookOpen className="w-8 h-8" />
            <span className="text-xl font-bold uppercase tracking-widest">
              Knowledge
            </span>
          </div>
          <h1 className="text-5xl md:text-7xl font-semibold tracking-tight uppercase">
            Publications
          </h1>
          <p className="text-muted-foreground text-xl font-light max-w-2xl">
            Journals, research papers, and guides generated by our community.
          </p>
        </div>

        {publications.length === 0 ? (
          <div className="flex flex-col items-center gap-6 py-20 border border-dashed border-border/40 rounded-3xl">
            <p className="text-muted-foreground text-lg italic text-center">
              Our library is currently being organized. <br /> Important
              documents and research results coming soon.
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {publications.map((doc) => (
              <GlassCard
                key={doc.id}
                className="group hover:border-primary/40 transition-all"
              >
                <div className="flex flex-col md:flex-row gap-8">
                  <div className="w-full md:w-32 h-40 bg-primary/5 rounded-xl border border-primary/10 flex flex-col items-center justify-center p-4 text-center gap-4 group-hover:bg-primary/10 transition-colors">
                    <BookOpen className="w-8 h-8 text-primary" />
                    <span className="text-[10px] font-bold uppercase tracking-widest text-primary/60">
                      Research Paper
                    </span>
                  </div>
                  <div className="flex-1 flex flex-col gap-4">
                    <h3 className="text-2xl font-bold uppercase tracking-tight leading-tight group-hover:text-primary transition-colors">
                      {doc.title}
                    </h3>
                    <div className="flex items-center gap-2 text-xs font-semibold text-muted-foreground uppercase tracking-widest">
                      <User size={14} /> {doc.authors || "FRL Core Team"}
                    </div>
                    <p className="text-muted-foreground font-light leading-relaxed line-clamp-2">
                      {doc.summary}
                    </p>
                    <div className="mt-2">
                      <a
                        href={doc.pdfUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                      >
                        <Button className="flex items-center gap-2 px-6">
                          <Download size={16} /> Download PDF
                        </Button>
                      </a>
                    </div>
                  </div>
                </div>
              </GlassCard>
            ))}
          </div>
        )}

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex justify-center items-center gap-6 pt-12 border-t border-border/40">
            <button
              onClick={() => setPage((p) => Math.max(1, p - 1))}
              disabled={page === 1}
              className="text-xs font-bold uppercase tracking-widest px-8 py-4 rounded-full border border-border hover:border-primary hover:text-primary transition-all disabled:opacity-30 disabled:hover:border-border disabled:hover:text-foreground"
            >
              ΓåÉ Previous
            </button>
            <span className="text-sm font-bold opacity-50 uppercase tracking-widest">
              Page {page} of {totalPages}
            </span>
            <button
              onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
              disabled={page === totalPages}
              className="text-xs font-bold uppercase tracking-widest px-8 py-4 rounded-full border border-border hover:border-primary hover:text-primary transition-all disabled:opacity-30 disabled:hover:border-border disabled:hover:text-foreground"
            >
              Next ΓåÆ
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
